//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdiEntidadesGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdiGeneraDocumentoDeVenta
    {
        public string tipoDocumento { get; set; }
        public string emisorNroDoc { get; set; }
        public string emisorNombre { get; set; }
        public string emisorUbigeo { get; set; }
        public string emisorDireccion { get; set; }
        public string emisorUrbanizacion { get; set; }
        public string emisorDepartamento { get; set; }
        public string emisorProvincia { get; set; }
        public string emisorDistrito { get; set; }
        public string receptorTipoDoc { get; set; }
        public string receptorNroDoc { get; set; }
        public string receptorNombre { get; set; }
        public string idDocumento { get; set; }
        public Nullable<System.DateTime> fechaEmision { get; set; }
        public string moneda { get; set; }
        public string tipoOperacion { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> ivaTasa { get; set; }
        public decimal ivaImponible { get; set; }
        public decimal iva { get; set; }
        public decimal inafecta { get; set; }
        public decimal exonerado { get; set; }
        public decimal xchgrate { get; set; }
        public decimal total { get; set; }
        public short soptype { get; set; }
        public string sopnumbe { get; set; }
        public decimal ORTDISAM { get; set; }
    }
}
